name: kube-prometheus-stack
apiVersion: v2
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 72.9.1
    repository: https://prometheus-community.github.io/helm-charts
    alias: kps
  - name: cluster-common
    version: "0.1.0"
    repository: "https://omer-bar.github.io/Homelab/charts/"